---
- name: Yolo
  hosts: all
  become: true
  vars:
    - directory: /home/vagrant/yolo
  tasks:
    - name: Update Server
      apt:
        update_cache: true
    
    - name: Install Git
      apt:
        name: git
        state: present
    
    - name: Clone Yolo Repository
      git:
        repo: https://github.com/Moses-Maina-ctrl/yolo.git
        dest: "{{ directory }}"

    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
    
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker SDK
      pip:
        name: docker-compose


    - name: Start Docker Containers
      docker_compose:
        project_src: "{{ directory }}"
        state: present