---
- name: Yolo
  hosts: all
  become: true
  vars:
    - directory: /home/vagrant
  tasks:
    - name: Update Server
      apt:
        update_cache: true
    
    - name: Install Git
      apt:
        name: git
        state: present
    
    - name: Clone Yolo Repository
      git:
        repo: https://github.com/Moses-Maina-ctrl/yolo.git
        dest: "{{ directory }}/yolo"