---
- name: Install required dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg
    state: latest
    update_cache: true

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install docker-compose using pip
  pip:
    name:
      - docker==5.0.3
      - docker-compose==1.29.2

- name: Create Directory for Docker's GPG Key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb  https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update Apt
  apt:
    update_cache: yes

- name: Install Docker and Docker Compose packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
